window.UNITS_BY_COST = {
  "1": [
    { name: "Mirana", race: ["Elf"], class: ["Hunter"] },
    { name: "Dark Willow", race: ["Elf"], class: ["Wizard"] },
    { name: "Witch Doctor", race: ["Troll"], class: ["Warlock"] },
    { name: "Shadow Shaman", race: ["Troll"], class: ["Shaman"] },
    { name: "Dazzle", race: ["Troll"], class: ["Priest"] },
    { name: "Tusk", race: ["Beast"], class: ["Warrior"] },
    { name: "Hoodwink", race: ["Beast"], class: ["Hunter"] },
    { name: "Enchantress", race: ["Beast"], class: ["Druid"] },
    { name: "Crystal Maiden", race: ["Human"], class: ["Mage"] },
    { name: "Axe", race: ["Orc"], class: ["Warrior"] },
    { name: "Clockwerk", race: ["Goblin"], class: ["Mech"] },
    { name: "Tinker", race: ["Goblin"], class: ["Mech"] },
    { name: "Ancient Apparition", race: ["Elemental"], class: ["Mage"] },
    { name: "Mars", race: ["God"], class: ["Warrior"] },
    { name: "Brewmaster", race: ["Pandaren"], class: ["Monk"] },
    { name: "Spirit Breaker", race: ["Tauren"], class: ["Assassin"] },
    { name: "Bane", race: ["Satyr", "Faceless"], class: ["Warlock"] },
    { name: "Bounty Hunter", race: ["Draenei", "Goblin"], class: ["Hunter"] },
    { name: "Shadow Demon", race: ["Draenei", "Demon"], class: ["Priest"] },
    { name: "Skywrath Mage", race: ["Harpy"], class: ["Mage"] },
    { name: "Clinkz", race: ["Undead"], class: ["Hunter"] },
    { name: "Abaddon", race: ["Undead"], class: ["Knight"] },
    { name: "Winter Wyvern", race: ["Dragon", "Undead"], class: ["Mage"] }
  ],
  "2": [
    { name: "Windranger", race: ["Elf"], class: ["Hunter"] },
    { name: "Luna", race: ["Elf"], class: ["Knight"] },
    { name: "Puck", race: ["Elf", "Dragon"], class: ["Mage"] },
    { name: "Furion", race: ["Elf"], class: ["Druid"] },
    { name: "Batrider", race: ["Troll"], class: ["Knight"] },
    { name: "Lina", race: ["Human"], class: ["Mage"] },
    { name: "Juggernaut", race: ["Orc"], class: ["Warrior"] },
    { name: "Beastmaster", race: ["Orc"], class: ["Hunter"] },
    { name: "Bloodseeker", race: ["Orc"], class: ["Shaman"] },
    { name: "Timbersaw", race: ["Goblin"], class: ["Mech"] },
    { name: "Slark", race: ["Naga"], class: ["Assassin"] },
    { name: "Largo", race: ["Naga"], class: ["Monk"] },
    { name: "Tiny", race: ["Elemental"], class: ["Warrior"] },
    { name: "Oracle", race: ["God"], class: ["Priest"] },
    { name: "Sniper", race: ["Dwarf"], class: ["Hunter"] },
    { name: "Chaos Knight", race: ["Demon"], class: ["Knight"] },
    { name: "Meepo", race: ["Kobold"], class: ["Mech"] },
    { name: "Faceless Void", race: ["Faceless"], class: ["Assassin"] },
    { name: "Dark Seer", race: ["Draenei"], class: ["Warlock"] },
    { name: "Centaur Warrunner", race: ["Centaur"], class: ["Warrior"] },
    { name: "Muerta", race: ["Undead"], class: ["Hunter"] },
    { name: "Lifestealer", race: ["Undead", "Kobold"], class: ["Warlock"] },
    { name: "Vengeful Spirit", race: ["Undead", "Harpy"], class: ["Demon Hunter"] }
  ],
  "3": [
    { name: "Treant Protector", race: ["Elf"], class: ["Druid"] },
    { name: "Marci", race: ["Elf"], class: ["Monk"] },
    { name: "Huskar", race: ["Troll"], class: ["Warrior"] },
    { name: "Venomancer", race: ["Beast", "Aqir"], class: ["Warlock"] },
    { name: "Lycan", race: ["Human", "Beast"], class: ["Warrior"] },
    { name: "Legion Commander", race: ["Human"], class: ["Knight"] },
    { name: "Viper", race: ["Dragon"], class: ["Assassin"] },
    { name: "Slardar", race: ["Naga"], class: ["Warrior"] },
    { name: "Naga Siren", race: ["Naga"], class: ["Wizard"] },
    { name: "Enigma", race: ["Elemental"], class: ["Warlock"] },
    { name: "Razor", race: ["Elemental"], class: ["Shaman"] },
    { name: "Rubick", race: ["God"], class: ["Wizard"] },
    { name: "Sand King", race: ["Aqir"], class: ["Assassin"] },
    { name: "Ogre Magi", race: ["Ogre"], class: ["Mage"] },
    { name: "Shadow Fiend", race: ["Demon"], class: ["Warlock"] },
    { name: "Terrorblade", race: ["Demon"], class: ["Demon Hunter"] },
    { name: "Earthshaker", race: ["Tauren"], class: ["Shaman"] },
    { name: "Riki", race: ["Satyr"], class: ["Assassin"] },
    { name: "Dawnbreaker", race: ["Draenei"], class: ["Knight"] },
    { name: "Kez", race: ["Harpy"], class: ["Assassin"] },
    { name: "Pudge", race: ["Undead"], class: ["Warrior"] },
    { name: "Drow Ranger", race: ["Undead"], class: ["Hunter"] },
    { name: "Undying", race: ["Undead"], class: ["Priest"] }
  ],
  "4": [
    { name: "Phantom Assassin", race: ["Elf"], class: ["Assassin"] },
    { name: "Anti-Mage", race: ["Elf"], class: ["Demon Hunter"] },
    { name: "Pangolier", race: ["Beast"], class: ["Assassin"] },
    { name: "Lone Druid", race: ["Beast"], class: ["Druid"] },
    { name: "Monkey King", race: ["Beast"], class: ["Monk"] },
    { name: "Kunkka", race: ["Human"], class: ["Warrior"] },
    { name: "Keeper of the Light", race: ["Human"], class: ["Mage"] },
    { name: "Dragon Knight", race: ["Human", "Dragon"], class: ["Knight"] },
    { name: "Chen", race: ["Orc"], class: ["Priest"] },
    { name: "Snapfire", race: ["Goblin"], class: ["Knight"] },
    { name: "Alchemist", race: ["Goblin", "Ogre"], class: ["Warlock"] },
    { name: "Medusa", race: ["Naga"], class: ["Hunter"] },
    { name: "Phoenix", race: ["Elemental"], class: ["Mage"] },
    { name: "Elder Titan", race: ["Tauren", "God"], class: ["Druid"] },
    { name: "Broodmother", race: ["Aqir"], class: ["Hunter"] },
    { name: "Doom", race: ["Demon"], class: ["Warrior"] },
    { name: "Lion", race: ["Demon"], class: ["Wizard"] },
    { name: "Magnus", race: ["Centaur"], class: ["Assassin"] },
    { name: "Lich", race: ["Undead"], class: ["Mage"] },
    { name: "Death Prophet", race: ["Undead"], class: ["Warlock"] },
    { name: "Nyx Assassin", race: ["Aqir"], class: ["Assassin"] },
    { name: "Ember Spirit", race: ["Pandaren"], class: ["Assassin"] },
    { name: "Storm Spirit", race: ["Pandaren"], class: ["Mage"] },
    { name: "Earth Spirit", race: ["Pandaren"], class: ["Shaman"] },
    { name: "Void Spirit", race: ["Pandaren"], class: ["Monk"] }
  ],
  "5": [
    { name: "Templar Assassin", race: ["Elf"], class: ["Assassin"] },
    { name: "Invoker", race: ["Elf"], class: ["Mage"] },
    { name: "Troll Warlord", race: ["Troll"], class: ["Warrior"] },
    { name: "Primal Beast", race: ["Beast"], class: ["Warrior"] },
    { name: "Omniknight", race: ["Human"], class: ["Knight"] },
    { name: "Warlock", race: ["Orc"], class: ["Warlock"] },
    { name: "Disruptor", race: ["Orc"], class: ["Shaman"] },
    { name: "Techies", race: ["Goblin"], class: ["Mech"] },
    { name: "Jakiro", race: ["Dragon"], class: ["Mage"] },
    { name: "Tidehunter", race: ["Naga"], class: ["Hunter"] },
    { name: "Morphling", race: ["Elemental", "Elf"], class: ["Assassin"] },
    { name: "Zeus", race: ["God"], class: ["Mage"] },
    { name: "Leshrac", race: ["God", "Centaur"], class: ["Druid"] },
    { name: "Gyrocopter", race: ["Dwarf"], class: ["Mech"] },
    { name: "Sven", race: ["Demon"], class: ["Warrior"] },
    { name: "Queen of Pain", race: ["Demon"], class: ["Assassin"] },
    { name: "Abyssal Underlord", race: ["Demon"], class: ["Warlock"] },
    { name: "Ringmaster", race: [], class: [] },
    { name: "Arc Warden", race: ["Kobold"], class: ["Shaman"] },
    { name: "Wraith King", race: ["Undead"], class: ["Knight"] },
    { name: "Necrophos", race: ["Undead"], class: ["Warlock"] },
    { name: "Spectre", race: ["Undead"], class: ["Demon Hunter"] },
    { name: "Io", race: ["Elf"], class: [] }
  ]
};
